
//para poner el nombre del dr


                ooo                
                ooo                
                o o                
               o   o               
              o     o              
             o       o             
            o         o            
           o           o           
 MMMMMMMMMNMMMMMMMMMMMMMNMMMMMNMMM 
M                                 M
M                                 M
M                                 M
M                                 M
M                                 M
M                                 M
M                                 M
M                                 M
M                                 M
M                                 M
 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM 


     //pacientes
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXNWMWNKKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOc,;cll;'';o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKd:'..........:OWMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMM
MMMMMMMMMMMMWWWWWWWWWWWWWWMMMMMMMMMMMMMMMXl.....',',;;lkXWMMMMMMMMMMMMMMMMMMMWWWWNNXXXXNWWWMMMMMMMMM
MMMMMMMMMWWWWWWWNNNNNNWWWWWWMMMMMMMMMMMMMXl....,:;;:::oKWWWWWMMMMMMMMMMMMMWWWWXOdolollodONWWWWMMMMMM
MMMMMMMMWWWWWNNNNNNNNNNNWWWWWWMMMMMMMMMWWW0l;,.;::::::l0WWWWWWWMMMMMMMMMMWWWWXd;:ll:::::ckNWWWWMMMMM
MMMMMMWWWWWWWNNNXXKKXXNNNWWWWWWWMMMMMMWWWWWXk:',;;;::;:ONWWWWWWWWMMMMMMWWWWWWOclkOkl:::::oKWWWWWMMMM
MMMMMWWWWWWWNNXKOkkkkOKNNNWWWWWWWMMMMWWWWWWWNx,','',,''oXWWWWWWWWMMMMMWWWWWWWOlxOOOxlc:::l0WWWWWWMMM
MMMMMWWWWWNNNNX0kkkkkOKXNNNWWWWWWMMMWWWWWWWWNk,.......'dNWWWWWWWWWMMMWWWWWWWWOlxkkkkxoc::lOWWWWWWWMM
MMMMWWWWWWWNNNXKOkkkkOKXNNNWWWWWWWMMWWWWNNNX0o:,''.,:ox0KXXNWWWWWWMMMWWWWWWWNk:lk0000xl::cxNWWWWWWMM
MMMMWWWWWWWWNNNNK0kkOKNNNWWWWWWWWWMMWWNX000OkxoolllokOOOOOOKNWWWWWWMMWWWWWWWXo,;lkOOkdc:::lkNWWWWWMM
MMMMWWWWWWWNNXXNN0kk0XXKKKXWWWWWWWMMWWX0OOOOOOOOkkOOOOkl;;:l0NWWWWMMMWWWWWWWKl,,,,;;,,::::;lKWWWWWMM
MMMMMWWWWWNOxddxkOkkkxdooox0NWWWWMMMWWX0OOOOOOOOOOOOOOx,   .dNWWWWMMMMWWWWWWXl........;::,..:0WWWWMM
MMMMMMWWWNOoooool:;;;:looood0NWWMMMMMWX0OOOOOOOOOOOOOko,''';dKWWWMMMMMWWWWNNO,...............cKWWMMM
MMMMMMMWNOdoooooc....'coooooxKWMMMMMMMN0OOOOOkkOOOOOOx;',:::o0WWMMMMMMMNOdcc;. ..............'kWMMMM
MMMMMMMMXkoooooddoloodxdooodxKWMMMMMMMN0kkOOkxxxkkOOOd;..'::ckNMMMMMMMM0:.....'...'........'';kWMMMM
MMMMMMMMNOxxddxOxl:;;lkOxxxxkXWMMMMMMMMKdllodxddxxxxkkxxdlc::l0WMMMMMMMWO:,;,,:clxxxoc,...cxxOXMMMMM
MMMMMMMMXkxkkkOkc.   ,dkOOkkx0WMMMMMMMMXd:::ldddxxdddxxxkxl:::xNMMMMMMMMW0kd:.',,;,;lkOkdlx000XMMMMM
MMMMMMMWKkkkOOx:......,lkOOkk0NMMMMMMMMNd:::lddddddxddddddlc::oKMMMMMMMMWN0l,,:l;....,lx000000XWMMMM
MMMMMMMWKOOOOx:.........ckOOO0NMMMMMMMMWkc::cddddddxdddddddl::l0MMMMMMMMMMN0kO00kxdddddxkOO000NMMMMM
MMMMMMMMN0Oko;...........:dk0XWMMMMMMMMMXdc:codxddddddddxdddod0NMMMMMMMMMMMMWNX0OOOOOOOOOOO0XNWMMMMM
MMMMMMMMWNKo'.............'dXMMMMMMMMMMMWKo::lddddddddddddddkKWMMMMMMMMMMMMMMMWKOOOOOOOOOOOOXWMMMMMM
MMMMMMMMMMO,...............;0MMMMMMMMMMMMW0o:coddddddddxddddxXMMMMMMMMMMMMMMMMN0OOOOOOOOOOOO0NMMMMMM
MMMMMMMMMNo.................oNMMMMMMMMMMMMW0o:cllloooooooolldXMMMMMMMMMMMMMMMWKOOOOOOOOOOOOOOKWMMMMM
MMMMMMMMMK:.................:XMMMMMMMMMMMMMW0l:cllllllllllood0WMMMMMMMMMMMMMMN0OOOOOOOOOOOOOkOXMMMMM


